use_frameworks!
platform :ios, '10.0'

target 'SwiftJsonThemeManager_Example' do
  pod 'SwiftJsonThemeManager', :path => '../'

  target 'SwiftJsonThemeManager_Tests' do
    inherit! :search_paths

    
  end
end
